schema_version: 1

context:
  name: casttube
  version: 0.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/casttube-${{ version }}.tar.gz
  sha256: 54d2af8c7949aa9c5db87fb11ef0a478a5d3e7ac6d2d2ac8dd1711e3a516fc82

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests

tests:
  - python:
      imports:
        - casttube
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: YouTube chromecast api
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/ur1katz/casttube

extra:
  recipe-maintainers:
    - pavelzw
